### ISSUE TITLE
Comparing Fold Changes between runEdgeR and brew

### ISSUE THREAD

**Issue by FarzanehRah** [athchen/beer#6]
Hi,
I have some questions regarding the results obtained from running BEER on my data, specifically comparing the results of `runEdgeR`and `brew`. To better understand this, I decided to refer to your dataset (hiv.rds) available on [beer_manuscript](https://github.com/athchen/beer_manuscript) :

In the result of **HIV EC 9** sample, for example, for **_pep_19650_**, the _edgeR_logfc_ is **_1.52_** (fold change: **2.88**). However, the values for _beer_fc_marg (phi)_ and _beer_fc_cond (phi_Z)_ are **_8.37_**. 
I'm curious about the reason for this difference between the fold changes.
Additionally, in my case, _beer_fc_marg_ and _beer_fc_cond_ are not the same. Which one should I consider as the fold change?

![BEER_HIV_results](https://github.com/athchen/beer/assets/51157471/2cf5dd1e-7145-4cf8-a934-6913c7857032)

Thank you for your assistance in clarifying these points.

**Comment by athchen** [comment]
The difference in the fold-change is most likely due to the attenuation constant/competing resources effect that is discussed in the paper.

`beer_fc_marg` is the fold-change after after averaging over the probability that a given peptide is enriched. So for example, if the beer posterior probability that the peptide is enriched is 0.75 and if its enriched then the fold-change is 8.37, then the marginal fold-change is 1*(probability not enriched) + phi_enriched*(probability enriched) = 1*(0.25) + 8.37*(0.75). However, the `beer_fc_cond` (phi_Z) is basically the fold change depending on the prediction. So in same prior example, the posterior probability of enrichment is high, so `beer_fc_cond` will be the fold-change assuming enrichment, so 8.37. If the peptide is not predicted to be enriched, then the fold-change will be 1. 

For that peptide that you highlighted, the fold-change in both cases is 1 because the posterior probability of enrichment is 1. It may not be the case in your data because the posterior probability is a bit lower. 

As for what fold-change to use, it depends on what you are interested in. I think in most cases the `beer_fc_cond` is the one of interest since it conditions on the category (enriched/not-enriched) with highest posterior probability.

**Comment by FarzanehRah** [comment]
Thank you so much Athena, for the thorough explanation.
